### PR TITLE
Correct Postgres version in dev and CI

### PR DESCRIPTION
**Pull request by seanh**
LMS's staging and production environments use Postgres 15.5 not 15.6.

### CODE REVIEW

**Comment by marcospri** [comment]
This is not necessary as RDS will auto upgrade minor versions with the `Auto minor version upgrade` setting.

**Review by marcospri — CHANGES_REQUESTED** [review]
This is not necessary as RDS will auto upgrade minor versions with the Auto minor version upgrade setting.

**Comment by robertknight** [comment]
@seanh - Are you still intending to go ahead with this change across our repos? If not, this PRs should be closed.

**Comment by seanh** [comment]
> @seanh - Are you still intending to go ahead with this change across our repos? If not, this PRs should be closed.

I think let's close this. This PR is for the development and CI versions of Postgres (so these aren't auto-upgraded for us by RDS) but I think it's probably not worth the hassle of keeping the minor version up to date in dev and CI, we can probably risk letting this be out-of-date compared to production.

**Pull request closed without merging**
