### PR TITLE
Update canvas oauth buttons

### PR DESCRIPTION
**Pull request by LMS007**
~_Depends on https://github.com/hypothesis/lms/pull/2604_~

Test URL for auth

http://localhost:8001/canvas_oauth_callback?authUrl=blah

Test assignment for missing keys
https://hypothesis.instructure.com/courses/121/assignments/850

**Before**

Screen Shot 2021-04-27 at 2 40 39 PM

Screen Shot 2021-04-27 at 2 51 39 PM

**After**

Screen Shot 2021-04-27 at 3 27 40 PM

Screen Shot 2021-04-27 at 3 23 45 PM

### CODE REVIEW

**Comment by lyzadanger** [comment]
@LMS007 This branch contains an extra commit from #2604 . Can you fix the compare branch?

**Comment by lyzadanger** [comment]
> Test URL for auth

> http://localhost:8001/canvas_oauth_callback?authUrl=blah

Can you explain this a little more? Does this mean that I should hit that URL with LMS running locally? Or something else?

**Comment by LMS007** [comment]
> tains an extra commit from

that PR is merged now, no more dependency

**Comment by LMS007** [comment]
> > Test URL for auth
> 
> > http://localhost:8001/canvas_oauth_callback?authUrl=blah
> 
> Can you explain this a little more? Does this mean that I should hit that URL with LMS running locally? Or something else?

Yes exactly, if you run canvas locally, just put that URL in chrome, it should work

**Comment by lyzadanger** [comment]
> Yes exactly, if you run canvas locally, just put that URL in chrome, it should work

Can you clarify what you mean by _run canvas locally?_ Do you mean _run the LMS project locally_?

**Comment by LMS007** [comment]
> _locally?_ Do you mean _run the LMS project locally_

Sorry, LMS.

**Comment by lyzadanger** [comment]
> Test assignment for missing keys
> https://hypothesis.instructure.com/courses/121/assignments/850

@LMS007 Logged in as... ?

**Comment by lyzadanger** [comment]
Using the URL http://localhost:8001/canvas_oauth_callback?authUrl=blah (logged in as an instructor `eng+canvasteacher@hypothes.is`) I am not seeing the "Try Again" button (I do see the _Close_ button).

**Comment by LMS007** [comment]
> Using the URL http://localhost:8001/canvas_oauth_callback?authUrl=blah (logged in as an instructor `eng+canvasteacher@hypothes.is`) I am not seeing the _Try Again_ button (I do see the _Close_ button).

Awe right..  I'm not sure if we have an assignment set up to exactly trigger this state in the UI, so it may require some tampering. Add this to the root `frontend_apps/index.js` before the switch statement and then you can see the try again button.

```
if (config.canvasOAuth2RedirectError) {
  config.canvasOAuth2RedirectError.authUrl = 'foo';
}
```

Then use this assignment. https://hypothesis.instructure.com/courses/121/assignments/850
The first popup will likley be authorize, then you should see the oauth dialog in a separate window. At some point a dialog testing page will be useful for lms in the future.

**Review by lyzadanger — APPROVED** [review]
Cool. Was able to test.

**Pull request merged**
