### PR TITLE
Update text on new_application_instance.html.jinja2

### PR DESCRIPTION
**Pull request by klemay**
Fixes https://github.com/hypothesis/lms/issues/1781.

### CODE REVIEW

**Comment by lyzadanger** [comment]
@klemay As an uninformed reader, I don't know what "Please note that these features may not be implemented separately" means. Do we expect the audience for this form to understand?

**Comment by klemay** [comment]
@lyzadanger Yes, it's meant to communicate that "you can't turn on one but not the other?" - we expect that an LMS admin would know what this means but I welcome a suggestion for wording this more clearly if you can think of a way!

**Comment by lyzadanger** [comment]
@klemay I think I'm tripping over the word "implemented." Perhaps even just changing that to "activated"?

**Comment by klemay** [comment]
@lyzadanger how about sticking with "enabled," used in the previous sentence? 

> The following fields are only needed if you are using the Canvas LMS and would like to enable the file picker and sections features. Please note that these features may not be enabled separately.</p>

**Comment by lyzadanger** [comment]
@klemay Looks good!

**Comment by klemay** [comment]
@lyzadanger awesome, done! and thanks for flagging that potentially confusing language!

**Comment by lyzadanger** [comment]
Looks good. I'm going to merge for yah.

**Pull request merged**
