### PR TITLE
Update language about Canvas dev credentials

### PR DESCRIPTION
**Pull request by mattdricker**
Update language about features enabled by using Canvas dev credentials and include link to KB

### CODE REVIEW

**Comment by mattdricker** [comment]
Hi Rob, saw you hopped on this quick! I realized I had the wrong URL in the link, so I converted to draft to make the change

**Comment by mattdricker** [comment]
Ready for review

**Comment by robertknight** [comment]
The changes look good to me. I tried to wrap the long line for readability but I don't have permission because this PR was created from your `master` branch. What I suggest doing in future is to create a new branch for any PRs and make sure to check the option to give maintainers the ability to push to it when creating the PR.

**Comment by mattdricker** [comment]
Thank you!

**Pull request merged**
