### PR TITLE
Always deploy the correct Docker image version

### PR DESCRIPTION
**Pull request by seanh**
Fixes https://github.com/hypothesis/lms/issues/4588. For details see: https://github.com/hypothesis/via/pull/814

### CODE REVIEW

**Comment by indigobravo** [comment]
Heads up on this one. Conflicts will need to be fixed.


I removed the job level concurrency options from deploy.yml for LMS. It has been reverted back to a known working state. This was to help fix the problem Lyza was running into. https://github.com/hypothesis/lms/pull/4595

**Review by indigobravo — CHANGES_REQUESTED** [review]
Heads up on this one. Conflicts will need to be fixed.


I removed the job level concurrency options from deploy.yml for LMS. It has been reverted back to a known working state. This was to help fix the problem Lyza was running into. https://github.com/hypothesis/lms/pull/4595

**Comment by seanh** [comment]
Good catch and thanks for that revert, it was the right decision.  I'll rebase this next week...

**Comment by seanh** [comment]
Rebased

**Pull request merged**
