### PR TITLE
Removing duplicate tests which are covered by the gherkin tests

### PR DESCRIPTION
**Pull request by jon-betts**
* Also renamed the remaining tests
 * Left most of the infrastructure in place in-case we want it again
 * We have lost some coverage of un-configured launches
 * The configured ones are covered better in gherkin though

This is for: https://github.com/hypothesis/lms/issues/1220

### CODE REVIEW

**Comment by lyzadanger** [comment]
Before I review this, can you help provide a little context? The PR summary is that this is removing tests that are covered by gherkin, but in the diff it's gherkin tests that are being removed and functional tests are _added_—so this humble dev got confused.

**Comment by jon-betts** [comment]
Oh god, it's not that, it's just that the diff is really goofy.

A quick summary of changes:

 * Everything in this change is in `tests/functional` so no gherkin tests are effected
 * `lti_certification/test_lti_certification_1_1.py` has moved to `api/basic_lti_launch.py`
    * :warning: Git missed this! This is why it looks so daft
    * That file now contains a single happy path test and the machinery required for it
    * All the sections about LTI this and that have gone
 * Renamed the fixtures to be non-lti specific (they are just "good parameters" now)
 * Removed the other fixtures for section 4

**Comment by lyzadanger** [comment]
> ⚠️ Git missed this! This is why it looks so daft

Is this then a `git mv` operation primarily that got misinterpreted? That is, does the file `api/basic_lti_launch.py` have meaningful _new_ code in it that needs review? Or can I give that a light scan (as it was pre-existing for the most part)?

**Comment by jon-betts** [comment]
A light scan. The only difference is some parts are gone and some are renamed. I'll try and create a diff locally and paste it here.

**Comment by jon-betts** [comment]
```diff
--- test_lti_certification_1_1.py	2019-12-17 15:16:47.525880025 +0000
+++ basic_lti_launch.py	2019-12-17 15:16:39.093842818 +0000
@@ -1,6 +1,5 @@
 import re
 import time
-from urllib.parse import parse_qs, urlparse
 
 import oauthlib.common
 import oauthlib.oauth1
@@ -12,187 +11,18 @@
 from tests.functional.base_class import TestBaseClass
 
 
-class TestLTICertification(TestBaseClass):
+class TestBasicLTILaunch(TestBaseClass):
     SHARED_SECRET = "TEST_SECRET"
     OAUTH_CONSUMER_KEY = "Hypothesis1b40eafba184a131307049e01e9c147d"
     OAUTH_NONCE = "38d6db30e395417659d068164ca95169"
     OAUTH_CLIENT = oauthlib.oauth1.Client(OAUTH_CONSUMER_KEY, SHARED_SECRET)
 
     @pytest.mark.usefixtures("http_intercept")
-    def test_a_good_request_loads_fine(self, app, lti_params_1x):
-        result = self.lti_launch(app, lti_params_1x, status=200)
+    def test_a_good_request_loads_fine(self, app, lti_params):
+        result = self.lti_launch(app, lti_params, status=200)
 
         self.assert_response_is_html(result)
 
-    def test_1_1_redirect_to_tool_consumer_when_resource_link_id_missing(
-        self, app, lti_params_1x
-    ):
-        """
-        No resource_link_id provided.
-
-        Expected result: Return user to the Tool Consumer with an error message.
-        """
-        lti_params_1x.pop("resource_link_id")
-
-        self.assert_redirected_to_tool_with_message(
-            app, lti_params_1x, message=Any.string.containing("resource_link_id")
-        )
-
-    def test_1_2_nice_message_when_res_link_id_and_return_url_missing(
-        self, app, lti_params_1x
-    ):
-        """
-        No resource_link_id or return URL provided.
-
-        Expected result: A user-friendly error message.
-        """
-        lti_params_1x.pop("resource_link_id")
-        lti_params_1x.pop("launch_presentation_return_url")
-
-        result = self.lti_launch(app, lti_params_1x, status=422)
-
-        self.assert_response_is_html(result)
-        assert "resource_link_id" in result
-
-    def test_1_5_redirect_to_tool_consumer_when_lti_version_invalid(
-        self, app, lti_params_1x
-    ):
-        """
-        Invalid LTI version.
-
-        Return user to the Tool Consumer with an error message.
-        """
-        lti_params_1x["lti_version"] = "LTI-1"
-
-        self.assert_redirected_to_tool_with_message(
-            app, lti_params_1x, message=Any.string.containing("lti_version")
-        )
-
-    def test_1_6_redirect_to_tool_consumer_when_lti_version_wrong(
-        self, app, lti_params_1x
-    ):
-        """
-        Wrong LTI version.
-
-        Expected result: Return user to the Tool Consumer with an error message.
-                """
-        lti_params_1x["lti_version"] = "LTI-2p0"
-
-        self.assert_redirected_to_tool_with_message(
-            app, lti_params_1x, message=Any.string.containing("lti_version")
-        )
-
-    def test_1_7_redirect_to_tool_consumer_when_lti_version_missing(
-        self, app, lti_params_1x
-    ):
-        """
-        Missing LTI version.
-
-        Expected result: Return user to the Tool Consumer with an error message.
-        """
-        lti_params_1x.pop("lti_version")
-
-        self.assert_redirected_to_tool_with_message(
-            app, lti_params_1x, message=Any.string.containing("lti_version")
-        )
-
-    def test_1_8_redirect_to_tool_consumer_when_lti_mesage_type_invalid(
-        self, app, lti_params_1x
-    ):
-        """
-        Invalid LTI message type.
-
-        Expected result: Return user to the Tool Consumer with an error message.
-        """
-        lti_params_1x["lti_message_type"] = "a-basic-lti-launch-request"
-
-        self.assert_redirected_to_tool_with_message(
-            app, lti_params_1x, message=Any.string.containing("lti_message_type")
-        )
-
-    def test_1_9_redirect_to_tool_consumer_when_lti_message_type_missing(
-        self, app, lti_params_1x
-    ):
-        """
-        Missing LTI message type
-
-        Expected result: Return user to the Tool Consumer with an error message.
-        """
-        lti_params_1x.pop("lti_message_type")
-
-        self.assert_redirected_to_tool_with_message(
-            app, lti_params_1x, message=Any.string.containing("lti_message_type")
-        )
-
-    def test_4_5_redirect_to_tool_for_instructor_with_no_context_bar_id(
-        self, app, lti_params_4x
-    ):
-        """
-        Launch as an instructor with no context or personal information apart
-        from the context ID.
-
-        Expected result: User should have privileges appropriate to an
-        instructor (e.g. able to edit) unless context and/or personal information
-        is required in which case access should be denied and the user returned
-        to the Tool Consumer with a user-friendly message
-
-        Hypotheis note: context_title is required for us
-        See: See: https://github.com/hypothesis/lms/wiki/LTI-Parameters-Required-for-Hypothesis-LMS-App-Integration
-        """
-        lti_params_4x = self.update_params(
-            lti_params_4x,
-            remove=[
-                "context_label",
-                "context_title",
-                "context_type",
-                "lis_course_section_sourcedid",
-                "lis_person_contact_email_primary",
-                "lis_person_name_family",
-                "lis_person_name_full",
-                "lis_person_name_given",
-                "resource_link_title",
-            ],
-        )
-
-        self.assert_redirected_to_tool_with_message(
-            app, lti_params_4x, message=Any.string.matching(".*")
-        )
-
-    def test_4_6_redirect_to_tool_for_instructor_with_no_context(
-        self, app, lti_params_4x
-    ):
-        """
-        Launch as Instructor with no context information.
-
-        Expected result: User should have privileges appropriate to an
-        instructor (e.g. able to edit) unless context and/or personal
-        information is required in which case access should be denied and
-        the user returned to the Tool Consumer with a user-friendly message.
-
-        Hypotheis note: context_id and context_title are required for us:
-        See: https://github.com/hypothesis/lms/wiki/LTI-Parameters-Required-for-Hypothesis-LMS-App-Integration
-        """
-
-        lti_params_4x = self.update_params(
-            lti_params_4x,
-            remove=[
-                "context_id",
-                "context_label",
-                "context_title",
-                "context_type",
-                "custom_context_setting_url",
-                "custom_link_setting_url",
-                "lis_course_section_sourcedid",
-                "resource_link_title",
-            ],
-            # I've no idea why this is different, but it's in the spec tests
-            add={"custom_context_memberships_url": "$ToolProxyBinding.memberships.url"},
-        )
-
-        self.assert_redirected_to_tool_with_message(
-            app, lti_params_4x, message=Any.string.matching(".*")
-        )
-
     # ---------------------------------------------------------------------- #
     # Assertions
 
@@ -201,33 +31,10 @@
         assert response.headers["Content-Type"] == Any.string.matching("^text/html")
         assert response.html
 
-    @classmethod
-    def assert_redirected_to_tool_with_message(
-        cls, app, lti_params_1x, message=Any.string()
-    ):
-        response = cls.lti_launch(app, lti_params_1x, status=302)
-
-        expected_url = lti_params_1x["launch_presentation_return_url"]
-        url = urlparse(response.headers["Location"])
-
-        assert url._replace(query=None).geturl() == expected_url
-        assert parse_qs(url.query) == Any.dict.containing({"lti_msg": [message]})
-
     # ---------------------------------------------------------------------- #
     # Helper methods
 
     @classmethod
-    def update_params(cls, params, remove=None, add=None):
-        if remove:
-            for item in remove:
-                params.pop(item)
-
-        if add:
-            params.update(add)
-
-        return params
-
-    @classmethod
     def lti_launch(cls, app, params, status=200):
         url = "/lti_launches"
 
@@ -293,14 +100,8 @@
         return module_item_configuration
 
     @pytest.fixture
-    def lti_params_1x(self):
-        """LTI launch params for testing section 1.x tests."""
-        return self.json_fixture("lti_certification/v1.1/section_1.json")
-
-    @pytest.fixture
-    def lti_params_4x(self):
-        """LTI launch params for testing section 4.x tests."""
-        return self.json_fixture("lti_certification/v1.1/section_4.json")
+    def lti_params(self):
+        return self.json_fixture("lti_params/good_params.json")
 
     @pytest.yield_fixture
     def http_intercept(self, _http_intercept):
```

**Pull request merged**
