### PR TITLE
Update LMSFilePIcker buttons

### PR DESCRIPTION
**Pull request by LMS007**
~depends on https://github.com/hypothesis/lms/pull/2604~

Use this assignment (login as Hypothesis 101 Teacher)

https://hypothesis.instructure.com/courses/125/assignments/1257

From there you can click the button to Select a PDF

**Before**
Screen Shot 2021-04-28 at 2 14 10 PM
Screen Shot 2021-04-28 at 2 14 16 PM
Apr-28-2021 16-25-53

**After**
Apr-28-2021 16-47-20

Apr-28-2021 16-28-38

### CODE REVIEW

**Comment by lyzadanger** [comment]
@LMS007 This still cites a dependency.

**Comment by lyzadanger** [comment]
@LMS007 Can you provide instructions, links, users I should use to get to the interface that this PR pertains to?

**Comment by LMS007** [comment]
> @LMS007 Can you provide instructions, links, users I should use to get to the interface that this PR pertains to?

yep!

**updated description

**Review by lyzadanger — APPROVED** [review]
Thank you for working through this!

**Pull request merged**
