### PR TITLE
Rename authorizeUrl to authUrl

### PR DESCRIPTION
**Pull request by seanh**
And authorize_url to auth_url.

This is for consistency with other parts of the JS config where the same URL appears as authUrl.

### CODE REVIEW

**Review by jon-betts — APPROVED** [review]
This is a straight rename, and given all the tests are passing, I think this is pretty safe

**Comment by seanh** [comment]
I'm gonna wait for @robertknight 's review on this one, since it involves a lot of frontend changes

**Review by robertknight — APPROVED** [review]
This looks fine to me, aside from the merge conflicts that need to be resolved.

**Comment by seanh** [comment]
I've rebased this but it seems to break the frontend: if you click <kbd>Cancel</kbd> instead of <kbd>Authorise</kbd> in the popup window then no <kbd>Try again</kbd> button is shown on the error dialog in the popup window, on this branch

**Comment by seanh** [comment]
Ok that should be fixed now

**Pull request merged**
