### PR TITLE
Remove the new_oauth feature flag

### PR DESCRIPTION
**Pull request by seanh**
This is turned on for everyone now.

### CODE REVIEW

**Comment by robertknight** [comment]
The app crashes on startup with a configuration error due to conflicting view configurations:

```
09:23:17 backend.1  |   File "/Users/robert/.virtualenvs/h-lms/lib/python3.6/site-packages/pyramid/config/actions.py", l
ine 293, in execute_actions
09:23:17 backend.1  |     action = next(action_iter, None)
09:23:17 backend.1  |   File "/Users/robert/.virtualenvs/h-lms/lib/python3.6/site-packages/pyramid/config/actions.py", l
ine 484, in resolveConflicts
09:23:17 backend.1  |     raise ConfigurationConflictError(conflicts)
09:23:17 backend.1  | pyramid.exceptions.ConfigurationConflictError: Conflicting configuration actions
09:23:17 backend.1  |   For: ('view', None, '', 'canvas_oauth_callback', 'a9204cf84fd843dac4e2dad4c4b72fed')
09:23:17 backend.1  |     Line 42 of file /Users/robert/hypothesis/repos/lms/lms/views/api/canvas/authorize.py:
09:23:17 backend.1  |         schema=CanvasOAuthCallbackSchema,
09:23:17 backend.1  |     Line 17 of file /Users/robert/hypothesis/repos/lms/lms/views/oauth.py:
09:23:17 backend.1  |         @view_config(route_name="canvas_oauth_callback", request_method="GET")
09:23:17 backend.1  | [2019-07-17 09:23:17 +0100] [35987] [INFO] Worker exiting (pid: 35987)
```

Does this depend on other PRs?

**Comment by seanh** [comment]
Yeah, sorry, it depends on https://github.com/hypothesis/lms/pull/828

**Comment by robertknight** [comment]
Rebased.

**Comment by seanh** [comment]
RIght, the contents of the `/flags` page is set by an envvar and is independent of whether the code actually uses the flag or not. It'd be nice to make the list of flags shown on that page be settable in the DB and changeable using an admin page or API, because that's quicker and easier to do than changing an envvar.

**Pull request merged**
